"""Tests for the CAD tools that moved from templates/cad/ into doqs/scripts/.

FreeCAD is imported lazily inside the functions that need it, so the CSV and
path handling below runs under plain Python — this is the first time any of it
has been reachable from the test suite.
"""
from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_SCRIPTS = _REPO / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import cad_build  # noqa: E402
import cad_fingerprint  # noqa: E402
import cad_sync_params  # noqa: E402

_FIXTURE = _REPO / "tests" / "fixtures" / "minimal-machine"


class TestReadParams(unittest.TestCase):
    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-"))
        self.cad = self._tmp / "cad"
        self.cad.mkdir()

    def _write(self, text: str) -> None:
        (self.cad / "params.csv").write_text(text, encoding="utf-8")

    def test_missing_file_is_empty(self):
        self.assertEqual(cad_fingerprint.read_params(self.cad), {})

    def test_skips_generated_header_and_floats_values(self):
        self._write(
            "# generated by resolve_params.py — do not edit\n"
            "alias,value,unit,description\n"
            "rail_length,500,mm,Rail\n"
            "finish,anodised,,Surface\n"
        )
        self.assertEqual(
            cad_fingerprint.read_params(self.cad),
            {"rail_length": 500.0, "finish": "anodised"},
        )

    def test_blank_alias_rows_are_ignored(self):
        self._write("alias,value,unit,description\n,,,\nbore,8,mm,Bore\n")
        self.assertEqual(cad_fingerprint.read_params(self.cad), {"bore": 8.0})

    def test_header_without_required_columns_is_empty(self):
        self._write("name,amount\nrail_length,500\n")
        self.assertEqual(cad_fingerprint.read_params(self.cad), {})

    def test_explicit_path_wins_over_cad_dir(self):
        other = self._tmp / "elsewhere.csv"
        other.write_text("alias,value\nbore,3\n", encoding="utf-8")
        self.assertEqual(
            cad_fingerprint.read_params(self.cad, path=other), {"bore": 3.0}
        )


class TestSyncParamsRows(unittest.TestCase):
    def test_rows_skip_provenance_header(self):
        tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-")) / "params-table.csv"
        tmp.write_text(
            "# generated — do not edit\nconfiguration,rail_length\ndefault,300\n",
            encoding="utf-8",
        )
        self.assertEqual(
            cad_sync_params._rows(tmp),
            [["configuration", "rail_length"], ["default", "300"]],
        )


class TestFcstdPath(unittest.TestCase):
    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-"))
        self.cad = self._tmp / "cad"
        self.cad.mkdir()

    def _touch(self, *names: str) -> None:
        for name in names:
            (self.cad / name).write_bytes(b"")

    def test_no_document_raises(self):
        with self.assertRaises(RuntimeError) as ctx:
            cad_build.fcstd_path(self.cad)
        self.assertIn("No .FCStd", str(ctx.exception))

    def test_single_document_is_found(self):
        self._touch("rail.FCStd")
        self.assertEqual(cad_build.fcstd_path(self.cad), self.cad / "rail.FCStd")

    def test_several_without_document_raises(self):
        self._touch("rail.FCStd", "carriage.FCStd")
        with self.assertRaises(RuntimeError) as ctx:
            cad_build.fcstd_path(self.cad)
        self.assertIn("pass document=", str(ctx.exception))

    def test_several_with_document_selects(self):
        self._touch("rail.FCStd", "carriage.FCStd")
        self.assertEqual(
            cad_build.fcstd_path(self.cad, document="carriage"),
            self.cad / "carriage.FCStd",
        )


class TestLegacyToolCopyGate(unittest.TestCase):
    """validate_cad.py must reject the per-module copies this refactor removed."""

    def _run(self, root: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(_SCRIPTS / "validate_cad.py"), "--root", str(root)],
            capture_output=True,
            text=True,
            cwd=_REPO,
        )

    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-legacy-"))
        self.root = self._tmp / "machine"
        self.cad = self.root / "modules" / "x-axis" / "cad"
        self.cad.mkdir(parents=True)

    def test_clean_repo_passes(self):
        result = self._run(self.root)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("no stale DOQS tool copies", result.stdout)

    def test_copied_fingerprint_fails(self):
        (self.cad / "fingerprint.py").write_text("# copy\n", encoding="utf-8")
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("fingerprint.py", result.stdout)
        self.assertIn("cad_fingerprint.py", result.stdout)

    def test_copied_sync_params_fails(self):
        (self.cad / "sync_params.py").write_text("# copy\n", encoding="utf-8")
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("cad_sync_params.py", result.stdout)

    def test_legacy_build_model_fails(self):
        (self.cad / "build_model.py").write_text(
            "def open_document():\n    pass\n", encoding="utf-8"
        )
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("inlines the build scaffolding", result.stdout)

    def test_seeded_build_model_passes(self):
        seed = (_REPO / "templates" / "cad" / "build_model.py").read_text(
            encoding="utf-8"
        )
        (self.cad / "build_model.py").write_text(seed, encoding="utf-8")
        result = self._run(self.root)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


class TestSeedTemplate(unittest.TestCase):
    def test_seed_carries_no_scaffolding(self):
        seed = (_REPO / "templates" / "cad" / "build_model.py").read_text(
            encoding="utf-8"
        )
        self.assertIn("from cad_build import run", seed)
        for gone in ("def open_document(", "def run(", "openTransaction"):
            self.assertNotIn(gone, seed)

    def test_seed_bootstrap_finds_doqs_scripts(self):
        """The upward walk resolves from a module cad/ next to a doqs/ submodule."""
        tmp = Path(tempfile.mkdtemp(prefix="doqs-seed-"))
        cad = tmp / "modules" / "x-axis" / "cad"
        cad.mkdir(parents=True)
        (tmp / "doqs").symlink_to(_REPO, target_is_directory=True)
        seed = _REPO / "templates" / "cad" / "build_model.py"
        (cad / "build_model.py").write_bytes(seed.read_bytes())

        result = subprocess.run(
            [sys.executable, str(cad / "build_model.py")],
            capture_output=True,
            text=True,
        )
        # Without FreeCAD installed the run stops at the lazy `import FreeCAD`
        # inside cad_build.open_document. Getting that far is the assertion:
        # the upward walk found doqs/scripts and imported cad_build from it.
        self.assertIn("doqs/scripts/cad_build.py", result.stderr, result.stderr)
        self.assertIn("in open_document", result.stderr, result.stderr)
        self.assertNotIn("No module named 'cad_build'", result.stderr)
        self.assertNotIn("not found above", result.stderr)

    def test_templates_cad_holds_only_the_seed(self):
        """The scaffolding copies are gone; only the per-module seed remains."""
        names = sorted(
            p.name
            for p in (_REPO / "templates" / "cad").iterdir()
            if p.is_file()
        )
        self.assertEqual(names, ["build_model.py"])


if __name__ == "__main__":
    unittest.main()
