"""Tests for the CAD tools that moved from templates/cad/ into doqs/scripts/.

FreeCAD is imported lazily inside the functions that need it, so the CSV and
path handling below runs under plain Python — this is the first time any of it
has been reachable from the test suite.
"""
from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

_REPO = Path(__file__).resolve().parent.parent
_SCRIPTS = _REPO / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import cad_build  # noqa: E402
import cad_fingerprint  # noqa: E402
import cad_rules  # noqa: E402
import cad_sync_params  # noqa: E402

_FIXTURE = _REPO / "tests" / "fixtures" / "minimal-machine"


class TestReadParams(unittest.TestCase):
    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-"))
        self.cad = self._tmp / "cad"
        self.cad.mkdir()

    def _write(self, text: str) -> None:
        (self.cad / "params.csv").write_text(text, encoding="utf-8")

    def test_missing_file_is_empty(self):
        self.assertEqual(cad_fingerprint.read_params(self.cad), {})

    def test_skips_generated_header_and_floats_values(self):
        self._write(
            "# generated by resolve_params.py — do not edit\n"
            "alias,value,unit,description\n"
            "rail_length,500,mm,Rail\n"
            "finish,anodised,,Surface\n"
        )
        self.assertEqual(
            cad_fingerprint.read_params(self.cad),
            {"rail_length": 500.0, "finish": "anodised"},
        )

    def test_blank_alias_rows_are_ignored(self):
        self._write("alias,value,unit,description\n,,,\nbore,8,mm,Bore\n")
        self.assertEqual(cad_fingerprint.read_params(self.cad), {"bore": 8.0})

    def test_header_without_required_columns_is_empty(self):
        self._write("name,amount\nrail_length,500\n")
        self.assertEqual(cad_fingerprint.read_params(self.cad), {})

    def test_explicit_path_wins_over_cad_dir(self):
        other = self._tmp / "elsewhere.csv"
        other.write_text("alias,value\nbore,3\n", encoding="utf-8")
        self.assertEqual(
            cad_fingerprint.read_params(self.cad, path=other), {"bore": 3.0}
        )


class TestSyncParamsRows(unittest.TestCase):
    def test_rows_skip_provenance_header(self):
        tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-")) / "params-table.csv"
        tmp.write_text(
            "# generated — do not edit\nconfiguration,rail_length\ndefault,300\n",
            encoding="utf-8",
        )
        self.assertEqual(
            cad_sync_params._rows(tmp),
            [["configuration", "rail_length"], ["default", "300"]],
        )


class TestFcstdPath(unittest.TestCase):
    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-"))
        self.cad = self._tmp / "cad"
        self.cad.mkdir()

    def _touch(self, *names: str) -> None:
        for name in names:
            (self.cad / name).write_bytes(b"")

    def test_no_document_raises(self):
        with self.assertRaises(RuntimeError) as ctx:
            cad_build.fcstd_path(self.cad)
        self.assertIn("No .FCStd", str(ctx.exception))

    def test_single_document_is_found(self):
        self._touch("rail.FCStd")
        self.assertEqual(cad_build.fcstd_path(self.cad), self.cad / "rail.FCStd")

    def test_several_without_document_raises(self):
        self._touch("rail.FCStd", "carriage.FCStd")
        with self.assertRaises(RuntimeError) as ctx:
            cad_build.fcstd_path(self.cad)
        self.assertIn("pass document=", str(ctx.exception))

    def test_several_with_document_selects(self):
        self._touch("rail.FCStd", "carriage.FCStd")
        self.assertEqual(
            cad_build.fcstd_path(self.cad, document="carriage"),
            self.cad / "carriage.FCStd",
        )


class TestLegacyToolCopyGate(unittest.TestCase):
    """validate_cad.py must reject the per-module copies this refactor removed."""

    def _run(self, root: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(_SCRIPTS / "validate_cad.py"), "--root", str(root)],
            capture_output=True,
            text=True,
            cwd=_REPO,
        )

    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-legacy-"))
        self.root = self._tmp / "machine"
        self.cad = self.root / "modules" / "x-axis" / "cad"
        self.cad.mkdir(parents=True)

    def test_clean_repo_passes(self):
        result = self._run(self.root)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("no stale DOQS tool copies", result.stdout)

    def test_copied_fingerprint_fails(self):
        (self.cad / "fingerprint.py").write_text("# copy\n", encoding="utf-8")
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("fingerprint.py", result.stdout)
        self.assertIn("cad_fingerprint.py", result.stdout)

    def test_copied_sync_params_fails(self):
        (self.cad / "sync_params.py").write_text("# copy\n", encoding="utf-8")
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("cad_sync_params.py", result.stdout)

    def test_legacy_build_model_fails(self):
        (self.cad / "build_model.py").write_text(
            "def open_document():\n    pass\n", encoding="utf-8"
        )
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("inlines the build scaffolding", result.stdout)

    def test_seeded_build_model_passes(self):
        seed = (_REPO / "templates" / "cad" / "build_model.py").read_text(
            encoding="utf-8"
        )
        (self.cad / "build_model.py").write_text(seed, encoding="utf-8")
        result = self._run(self.root)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)


class TestSeedTemplate(unittest.TestCase):
    def test_seed_carries_no_scaffolding(self):
        seed = (_REPO / "templates" / "cad" / "build_model.py").read_text(
            encoding="utf-8"
        )
        self.assertIn("from cad_build import run", seed)
        for gone in ("def open_document(", "def run(", "openTransaction"):
            self.assertNotIn(gone, seed)

    def test_seed_bootstrap_finds_doqs_scripts(self):
        """The upward walk resolves from a module cad/ next to a doqs/ submodule."""
        tmp = Path(tempfile.mkdtemp(prefix="doqs-seed-"))
        cad = tmp / "modules" / "x-axis" / "cad"
        cad.mkdir(parents=True)
        (tmp / "doqs").symlink_to(_REPO, target_is_directory=True)
        seed = _REPO / "templates" / "cad" / "build_model.py"
        (cad / "build_model.py").write_bytes(seed.read_bytes())

        result = subprocess.run(
            [sys.executable, str(cad / "build_model.py")],
            capture_output=True,
            text=True,
        )
        # Without FreeCAD installed the run stops at the lazy `import FreeCAD`
        # inside cad_build.open_document. Getting that far is the assertion:
        # the upward walk found doqs/scripts and imported cad_build from it.
        self.assertIn("doqs/scripts/cad_build.py", result.stderr, result.stderr)
        self.assertIn("in open_document", result.stderr, result.stderr)
        self.assertNotIn("No module named 'cad_build'", result.stderr)
        self.assertNotIn("not found above", result.stderr)

    def test_templates_cad_holds_only_the_seed(self):
        """The scaffolding copies are gone; only the per-module seed remains."""
        names = sorted(
            p.name
            for p in (_REPO / "templates" / "cad").iterdir()
            if p.is_file()
        )
        self.assertEqual(names, ["build_model.py"])


def _load_freecad_stub():
    """Import tests/freecad_stub/FreeCAD.py under its own name, without side effects.

    The stub directory is deliberately not on sys.path — a stray top-level
    FreeCAD.py would shadow the real module for any later test.
    """
    path = _REPO / "tests" / "freecad_stub" / "FreeCAD.py"
    spec = importlib.util.spec_from_file_location("FreeCAD", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class TestSyncActiveSaveDiscipline(unittest.TestCase):
    """`save=False` is what lets an export leave the committed .FCStd alone.

    `cad_build.run()` already refuses to write a document it did not open;
    until now `sync_active()` had no way to make the same promise, so
    `export_variant.py` saved the source assembly on every export.
    """

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory(prefix="doqs-sync-")
        self.addCleanup(self._tmp.cleanup)
        tmp = Path(self._tmp.name)
        self.cad = tmp / "cad"
        self.cad.mkdir()
        (self.cad / "params.csv").write_text(
            "# generated by resolve_params.py — do not edit\n"
            "alias,value,unit,description\n"
            "rail_length,500,mm,Rail length\n"
            "rail_count,2,,How many rails\n",
            encoding="utf-8",
        )
        self.document = tmp / "stage.FCStd"
        self.document.write_text("ORIGINAL\n", encoding="utf-8")
        self.log = tmp / "journal.jsonl"

        self.stub = _load_freecad_stub()
        patcher = mock.patch.dict(sys.modules, {"FreeCAD": self.stub})
        patcher.start()
        self.addCleanup(patcher.stop)
        env = mock.patch.dict(os.environ, {"DOQS_FREECAD_STUB_LOG": str(self.log)})
        env.start()
        self.addCleanup(env.stop)

    def events(self):
        if not self.log.exists():
            return []
        return [json.loads(l)["event"] for l in self.log.read_text().splitlines()]

    def test_sync_active_saves_by_default(self):
        """The FreeCAD-console flow must keep working exactly as documented."""
        doc = self.stub.openDocument(self.document)
        cad_sync_params.sync_active(doc=doc, cad_dir=self.cad)
        self.assertIn("save", self.events())

    def test_sync_active_with_save_false_does_not_save(self):
        doc = self.stub.openDocument(self.document)
        before = self.document.read_bytes()
        updated = cad_sync_params.sync_active(doc=doc, cad_dir=self.cad, save=False)
        self.assertNotIn("save", self.events())
        self.assertIn("recompute", self.events())
        self.assertEqual(sorted(updated), ["rail_count", "rail_length"])
        self.assertEqual(self.document.read_bytes(), before)

    def test_sync_active_reads_an_explicit_csv_path(self):
        """csv_path wins over cad_dir — the mechanism export_variant relies on."""
        elsewhere = Path(self._tmp.name) / "staging"
        elsewhere.mkdir()
        (elsewhere / "params.csv").write_text(
            "alias,value,unit,description\nrail_length,800,mm,Rail length\n",
            encoding="utf-8",
        )
        doc = self.stub.openDocument(self.document)
        cad_sync_params.sync_active(
            doc=doc, csv_path=elsewhere / "params.csv", cad_dir=self.cad, save=False)
        sheet = doc.getObjectsByLabel("Params")[0]
        self.assertEqual(sheet.cells, {"rail_length": "800 mm"})


class _Vector:
    def __init__(self, x, y, z):
        self.x, self.y, self.z = x, y, z


class _BoundBox:
    XMin = YMin = ZMin = 0.0
    XMax = YMax = ZMax = 1.0


class _Shape:
    """A stand-in for a FreeCAD shape, built to expose only what a real one does.

    The real types differ in which centre-of-mass property they carry, and that
    difference is the whole point of the test: a solid has `CenterOfMass`, a
    compound has only `CenterOfGravity`, and a vertex has neither.
    """

    Volume = 10.0
    Area = 30.0
    Solids = [object()]
    Shells = [object()]
    Faces = [object(), object()]
    Edges = [object()]
    Vertexes = []

    def __init__(self, centre_of_mass=None, centre_of_gravity=None):
        self.BoundBox = _BoundBox()
        if centre_of_mass is not None:
            self.CenterOfMass = _Vector(*centre_of_mass)
        if centre_of_gravity is not None:
            self._centre_of_gravity = _Vector(*centre_of_gravity)

    def __getattr__(self, name):
        # A compound raises AttributeError for CenterOfMass; a massless shape
        # raises RuntimeError for CenterOfGravity. Reproduce both exactly.
        if name == "CenterOfGravity":
            centre = self.__dict__.get("_centre_of_gravity")
            if centre is None:
                raise RuntimeError("Cannot get center of gravity")
            return centre
        raise AttributeError(f"{type(self).__name__!r} object has no attribute {name!r}")

    def isValid(self):
        return True

    def isClosed(self):
        return True


class TestCentreOfMass(unittest.TestCase):
    """FreeCAD spreads the centre of mass over two properties. Cover both."""

    def test_solid_uses_center_of_mass(self):
        shape = _Shape(centre_of_mass=(1.0, 2.0, 3.0))
        self.assertEqual(cad_fingerprint._centre_of_mass(shape), [1.0, 2.0, 3.0])

    def test_compound_falls_back_to_center_of_gravity(self):
        """A compound has no CenterOfMass, and a compound is what a Body is.

        Before this fallback existed, every App::Part, App::Link, assembly,
        PartDesign Body and PartDesign feature raised AttributeError here, and
        a document of any real shape fingerprinted zero objects.
        """
        shape = _Shape(centre_of_gravity=(4.0, 5.0, 6.0))
        self.assertEqual(cad_fingerprint._centre_of_mass(shape), [4.0, 5.0, 6.0])

    def test_center_of_mass_wins_when_a_shape_has_both(self):
        shape = _Shape(centre_of_mass=(1.0, 2.0, 3.0), centre_of_gravity=(9.0, 9.0, 9.0))
        self.assertEqual(cad_fingerprint._centre_of_mass(shape), [1.0, 2.0, 3.0])

    def test_massless_shape_records_nothing(self):
        self.assertIsNone(cad_fingerprint._centre_of_mass(_Shape()))


class TestMeasureShape(unittest.TestCase):
    def test_a_compound_is_measured_in_full(self):
        measured = cad_fingerprint._measure_shape(
            _Shape(centre_of_gravity=(4.0, 5.0, 6.0)), cad_fingerprint.cad_rules)
        self.assertEqual(measured["com"], [4.0, 5.0, 6.0])
        self.assertEqual(measured["volume"], 10.0)
        self.assertEqual(measured["counts"]["faces"], 2)

    def test_a_massless_shape_is_still_measured(self):
        """No centre of mass must not cost the volume, the box and the counts."""
        measured = cad_fingerprint._measure_shape(_Shape(), cad_fingerprint.cad_rules)
        self.assertIsNone(measured["com"])
        self.assertEqual(measured["bbox"], [0.0, 0.0, 0.0, 1.0, 1.0, 1.0])

    def test_a_null_centre_survives_normalising_and_writing(self):
        """`com: null` must reach the file, not raise while rounding floats."""
        measured = cad_fingerprint._measure_shape(_Shape(), cad_fingerprint.cad_rules)
        self.assertIsNone(cad_rules.normalise({"objects": {"X": measured}})
                          ["objects"]["X"]["com"])


class TestMeasuredNothing(unittest.TestCase):
    """An empty fingerprint that reports success is how the bug stayed hidden."""

    def test_every_object_failing_is_reported(self):
        self.assertTrue(cad_rules.measured_nothing({"objects": {}, "errors": ["X: boom"]}))

    def test_a_document_with_no_geometry_stays_quiet(self):
        """A spreadsheet measures nothing and that is correct."""
        self.assertFalse(cad_rules.measured_nothing({"objects": {}, "errors": []}))

    def test_one_broken_feature_among_many_is_not_the_same_thing(self):
        self.assertFalse(
            cad_rules.measured_nothing({"objects": {"Pad": {}}, "errors": ["X: boom"]}))


class TestSkippedTypes(unittest.TestCase):
    def test_every_origin_datum_is_skipped(self):
        """The origin's point was missing while its line and plane were listed."""
        for type_id in ("App::Origin", "App::Line", "App::Plane", "App::Point"):
            self.assertTrue(
                type_id.startswith(cad_rules.SKIPPED_TYPE_PREFIXES),
                f"{type_id} should be skipped",
            )

    def test_real_content_is_not_skipped(self):
        for type_id in ("App::Part", "App::Link", "Assembly::AssemblyObject",
                        "PartDesign::Body", "PartDesign::Pad", "Part::Feature"):
            self.assertFalse(
                type_id.startswith(cad_rules.SKIPPED_TYPE_PREFIXES),
                f"{type_id} should be measured",
            )

if __name__ == "__main__":
    unittest.main()
