"""Tests for the CAD tools that moved from templates/cad/ into doqs/scripts/.

FreeCAD is imported lazily inside the functions that need it, so the CSV and
path handling below runs under plain Python — this is the first time any of it
has been reachable from the test suite.
"""
from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import types
import unittest
from pathlib import Path
from unittest import mock

_REPO = Path(__file__).resolve().parent.parent
_SCRIPTS = _REPO / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

import cad_build  # noqa: E402
import cad_fingerprint  # noqa: E402
import cad_rules  # noqa: E402
import cad_sync_params  # noqa: E402

_FIXTURE = _REPO / "tests" / "fixtures" / "minimal-machine"


class TestReadParams(unittest.TestCase):
    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-"))
        self.cad = self._tmp / "cad"
        self.cad.mkdir()

    def _write(self, text: str) -> None:
        (self.cad / "params.csv").write_text(text, encoding="utf-8")

    def test_missing_file_is_empty(self):
        self.assertEqual(cad_fingerprint.read_params(self.cad), {})

    def test_skips_generated_header_and_floats_values(self):
        self._write(
            "# generated by resolve_params.py — do not edit\n"
            "alias,value,unit,description\n"
            "rail_length,500,mm,Rail\n"
            "finish,anodised,,Surface\n"
        )
        self.assertEqual(
            cad_fingerprint.read_params(self.cad),
            {"rail_length": 500.0, "finish": "anodised"},
        )

    def test_blank_alias_rows_are_ignored(self):
        self._write("alias,value,unit,description\n,,,\nbore,8,mm,Bore\n")
        self.assertEqual(cad_fingerprint.read_params(self.cad), {"bore": 8.0})

    def test_header_without_required_columns_is_empty(self):
        self._write("name,amount\nrail_length,500\n")
        self.assertEqual(cad_fingerprint.read_params(self.cad), {})

    def test_explicit_path_wins_over_cad_dir(self):
        other = self._tmp / "elsewhere.csv"
        other.write_text("alias,value\nbore,3\n", encoding="utf-8")
        self.assertEqual(
            cad_fingerprint.read_params(self.cad, path=other), {"bore": 3.0}
        )


class TestSyncParamsRows(unittest.TestCase):
    def test_rows_skip_provenance_header(self):
        tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-")) / "params-table.csv"
        tmp.write_text(
            "# generated — do not edit\nconfiguration,rail_length\ndefault,300\n",
            encoding="utf-8",
        )
        self.assertEqual(
            cad_sync_params._rows(tmp),
            [["configuration", "rail_length"], ["default", "300"]],
        )


class TestFcstdPath(unittest.TestCase):
    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-"))
        self.cad = self._tmp / "cad"
        self.cad.mkdir()

    def _touch(self, *names: str) -> None:
        for name in names:
            (self.cad / name).write_bytes(b"")

    def test_no_document_raises(self):
        with self.assertRaises(RuntimeError) as ctx:
            cad_build.fcstd_path(self.cad)
        self.assertIn("No .FCStd", str(ctx.exception))

    def test_single_document_is_found(self):
        self._touch("rail.FCStd")
        self.assertEqual(cad_build.fcstd_path(self.cad), self.cad / "rail.FCStd")

    def test_several_without_document_raises(self):
        self._touch("rail.FCStd", "carriage.FCStd")
        with self.assertRaises(RuntimeError) as ctx:
            cad_build.fcstd_path(self.cad)
        self.assertIn("pass document=", str(ctx.exception))

    def test_several_with_document_selects(self):
        self._touch("rail.FCStd", "carriage.FCStd")
        self.assertEqual(
            cad_build.fcstd_path(self.cad, document="carriage"),
            self.cad / "carriage.FCStd",
        )


class TestParamsPath(unittest.TestCase):
    """A part built from cad/parts/<part>/ still reads the module's cad/params.csv."""

    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-cad-"))
        self.cad = self._tmp / "cad"
        self.part = self.cad / "parts" / "base"
        self.part.mkdir(parents=True)

    def test_module_cad_dir_walks_up_to_cad(self):
        self.assertEqual(cad_build.module_cad_dir(self.part), self.cad)
        self.assertEqual(cad_build.module_cad_dir(self.cad), self.cad)
        self.assertEqual(cad_build.module_cad_dir(self._tmp), self._tmp)

    def test_a_part_folder_reads_the_module_params(self):
        self.assertEqual(cad_build.params_path(self.part), self.cad / "params.csv")

    def test_a_params_file_beside_the_script_wins(self):
        (self.part / "params.csv").write_text("alias,value\n", encoding="utf-8")
        self.assertEqual(cad_build.params_path(self.part), self.part / "params.csv")

    def test_an_own_model_keeps_its_named_params(self):
        (self.part / "HGR20.params.csv").write_text("alias,value\n", encoding="utf-8")
        self.assertEqual(
            cad_build.params_path(self.part, document="HGR20"),
            self.part / "HGR20.params.csv",
        )


class TestLegacyToolCopyGate(unittest.TestCase):
    """validate_cad.py must reject the per-module copies this refactor removed."""

    def _run(self, root: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(_SCRIPTS / "validate_cad.py"), "--root", str(root)],
            capture_output=True,
            text=True,
            cwd=_REPO,
        )

    def setUp(self):
        self._tmp = Path(tempfile.mkdtemp(prefix="doqs-legacy-"))
        self.root = self._tmp / "machine"
        self.cad = self.root / "modules" / "x-axis" / "cad"
        self.cad.mkdir(parents=True)

    def test_clean_repo_passes(self):
        result = self._run(self.root)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("no stale DOQS tool copies", result.stdout)

    def test_copied_fingerprint_fails(self):
        (self.cad / "fingerprint.py").write_text("# copy\n", encoding="utf-8")
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("fingerprint.py", result.stdout)
        self.assertIn("cad_fingerprint.py", result.stdout)

    def test_copied_sync_params_fails(self):
        (self.cad / "sync_params.py").write_text("# copy\n", encoding="utf-8")
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("cad_sync_params.py", result.stdout)

    def test_legacy_build_model_fails(self):
        (self.cad / "build_model.py").write_text(
            "def open_document():\n    pass\n", encoding="utf-8"
        )
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("inlines the build scaffolding", result.stdout)

    def test_seeded_build_model_passes(self):
        seed = (_REPO / "templates" / "cad" / "build_model.py").read_text(
            encoding="utf-8"
        )
        (self.cad / "build_model.py").write_text(seed, encoding="utf-8")
        result = self._run(self.root)
        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_a_per_part_build_script_is_checked_too(self):
        part = self.cad / "parts" / "base"
        part.mkdir(parents=True)
        (part / "build_model.py").write_text(
            'if __name__ == "__main__":\n    pass\n', encoding="utf-8"
        )
        result = self._run(self.root)
        self.assertNotEqual(result.returncode, 0, result.stdout)
        self.assertIn("cad/parts/base/build_model.py", result.stdout)
        self.assertIn("main(build, globals())", result.stdout)


class TestSeedTemplate(unittest.TestCase):
    def test_seed_carries_no_scaffolding(self):
        seed = (_REPO / "templates" / "cad" / "build_model.py").read_text(
            encoding="utf-8"
        )
        self.assertRegex(seed, r"from cad_build import [^\n]*\bmain\b")
        for gone in ("def open_document(", "def run(", "openTransaction"):
            self.assertNotIn(gone, seed)

    def test_seed_bootstrap_finds_doqs_scripts(self):
        """The upward walk resolves from a module cad/ next to a doqs/ submodule."""
        tmp = Path(tempfile.mkdtemp(prefix="doqs-seed-"))
        cad = tmp / "modules" / "x-axis" / "cad"
        cad.mkdir(parents=True)
        (tmp / "doqs").symlink_to(_REPO, target_is_directory=True)
        seed = _REPO / "templates" / "cad" / "build_model.py"
        (cad / "build_model.py").write_bytes(seed.read_bytes())

        result = subprocess.run(
            [sys.executable, str(cad / "build_model.py")],
            capture_output=True,
            text=True,
        )
        # Without FreeCAD installed the run stops at the lazy `import FreeCAD`
        # inside cad_build.open_document. Getting that far is the assertion:
        # the upward walk found doqs/scripts and imported cad_build from it.
        self.assertIn("doqs/scripts/cad_build.py", result.stderr, result.stderr)
        self.assertIn("in open_document", result.stderr, result.stderr)
        self.assertNotIn("No module named 'cad_build'", result.stderr)
        self.assertNotIn("not found above", result.stderr)

    def test_templates_cad_holds_only_the_seed(self):
        """The scaffolding copies are gone; only the per-module seed remains."""
        names = sorted(
            p.name
            for p in (_REPO / "templates" / "cad").iterdir()
            if p.is_file()
        )
        self.assertEqual(names, ["build_model.py"])


def _load_freecad_stub():
    """Import tests/freecad_stub/FreeCAD.py under its own name, without side effects.

    The stub directory is deliberately not on sys.path — a stray top-level
    FreeCAD.py would shadow the real module for any later test.
    """
    path = _REPO / "tests" / "freecad_stub" / "FreeCAD.py"
    spec = importlib.util.spec_from_file_location("FreeCAD", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class TestSyncActiveSaveDiscipline(unittest.TestCase):
    """`save=False` is what lets an export leave the committed .FCStd alone.

    `cad_build.run()` already refuses to write a document it did not open;
    until now `sync_active()` had no way to make the same promise, so
    `export_variant.py` saved the source assembly on every export.
    """

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory(prefix="doqs-sync-")
        self.addCleanup(self._tmp.cleanup)
        tmp = Path(self._tmp.name)
        self.cad = tmp / "cad"
        self.cad.mkdir()
        (self.cad / "params.csv").write_text(
            "# generated by resolve_params.py — do not edit\n"
            "alias,value,unit,description\n"
            "rail_length,500,mm,Rail length\n"
            "rail_count,2,,How many rails\n",
            encoding="utf-8",
        )
        self.document = tmp / "stage.FCStd"
        self.document.write_text("ORIGINAL\n", encoding="utf-8")
        self.log = tmp / "journal.jsonl"

        self.stub = _load_freecad_stub()
        patcher = mock.patch.dict(sys.modules, {"FreeCAD": self.stub})
        patcher.start()
        self.addCleanup(patcher.stop)
        env = mock.patch.dict(os.environ, {"DOQS_FREECAD_STUB_LOG": str(self.log)})
        env.start()
        self.addCleanup(env.stop)

    def events(self):
        if not self.log.exists():
            return []
        return [json.loads(l)["event"] for l in self.log.read_text().splitlines()]

    def test_sync_active_saves_by_default(self):
        """The FreeCAD-console flow must keep working exactly as documented."""
        doc = self.stub.openDocument(self.document)
        cad_sync_params.sync_active(doc=doc, cad_dir=self.cad)
        self.assertIn("save", self.events())

    def test_sync_active_with_save_false_does_not_save(self):
        doc = self.stub.openDocument(self.document)
        before = self.document.read_bytes()
        updated = cad_sync_params.sync_active(doc=doc, cad_dir=self.cad, save=False)
        self.assertNotIn("save", self.events())
        self.assertIn("recompute", self.events())
        self.assertEqual(sorted(updated), ["rail_count", "rail_length"])
        self.assertEqual(self.document.read_bytes(), before)

    def test_sync_active_reads_an_explicit_csv_path(self):
        """csv_path wins over cad_dir — the mechanism export_variant relies on."""
        elsewhere = Path(self._tmp.name) / "staging"
        elsewhere.mkdir()
        (elsewhere / "params.csv").write_text(
            "alias,value,unit,description\nrail_length,800,mm,Rail length\n",
            encoding="utf-8",
        )
        doc = self.stub.openDocument(self.document)
        cad_sync_params.sync_active(
            doc=doc, csv_path=elsewhere / "params.csv", cad_dir=self.cad, save=False)
        sheet = doc.getObjectsByLabel("Params")[0]
        self.assertEqual(sheet.cells, {"rail_length": "800 mm"})


class _Vector:
    def __init__(self, x, y, z):
        self.x, self.y, self.z = x, y, z


class _BoundBox:
    XMin = YMin = ZMin = 0.0
    XMax = YMax = ZMax = 1.0


class _Shape:
    """A stand-in for a FreeCAD shape, built to expose only what a real one does.

    The real types differ in which centre-of-mass property they carry, and that
    difference is the whole point of the test: a solid has `CenterOfMass`, a
    compound has only `CenterOfGravity`, and a vertex has neither.
    """

    Volume = 10.0
    Area = 30.0
    Solids = [object()]
    Shells = [object()]
    Faces = [object(), object()]
    Edges = [object()]
    Vertexes = []

    def __init__(self, centre_of_mass=None, centre_of_gravity=None):
        self.BoundBox = _BoundBox()
        if centre_of_mass is not None:
            self.CenterOfMass = _Vector(*centre_of_mass)
        if centre_of_gravity is not None:
            self._centre_of_gravity = _Vector(*centre_of_gravity)

    def __getattr__(self, name):
        # A compound raises AttributeError for CenterOfMass; a massless shape
        # raises RuntimeError for CenterOfGravity. Reproduce both exactly.
        if name == "CenterOfGravity":
            centre = self.__dict__.get("_centre_of_gravity")
            if centre is None:
                raise RuntimeError("Cannot get center of gravity")
            return centre
        raise AttributeError(f"{type(self).__name__!r} object has no attribute {name!r}")

    def isValid(self):
        return True

    def isClosed(self):
        return True

    def isNull(self):
        return False


class TestCentreOfMass(unittest.TestCase):
    """FreeCAD spreads the centre of mass over two properties. Cover both."""

    def test_solid_uses_center_of_mass(self):
        shape = _Shape(centre_of_mass=(1.0, 2.0, 3.0))
        self.assertEqual(cad_fingerprint._centre_of_mass(shape), [1.0, 2.0, 3.0])

    def test_compound_falls_back_to_center_of_gravity(self):
        """A compound has no CenterOfMass, and a compound is what a Body is.

        Before this fallback existed, every App::Part, App::Link, assembly,
        PartDesign Body and PartDesign feature raised AttributeError here, and
        a document of any real shape fingerprinted zero objects.
        """
        shape = _Shape(centre_of_gravity=(4.0, 5.0, 6.0))
        self.assertEqual(cad_fingerprint._centre_of_mass(shape), [4.0, 5.0, 6.0])

    def test_center_of_mass_wins_when_a_shape_has_both(self):
        shape = _Shape(centre_of_mass=(1.0, 2.0, 3.0), centre_of_gravity=(9.0, 9.0, 9.0))
        self.assertEqual(cad_fingerprint._centre_of_mass(shape), [1.0, 2.0, 3.0])

    def test_massless_shape_records_nothing(self):
        self.assertIsNone(cad_fingerprint._centre_of_mass(_Shape()))


class TestMeasureShape(unittest.TestCase):
    def test_a_compound_is_measured_in_full(self):
        measured = cad_fingerprint._measure_shape(
            _Shape(centre_of_gravity=(4.0, 5.0, 6.0)), cad_fingerprint.cad_rules)
        self.assertEqual(measured["com"], [4.0, 5.0, 6.0])
        self.assertEqual(measured["volume"], 10.0)
        self.assertEqual(measured["counts"]["faces"], 2)

    def test_a_massless_shape_is_still_measured(self):
        """No centre of mass must not cost the volume, the box and the counts."""
        measured = cad_fingerprint._measure_shape(_Shape(), cad_fingerprint.cad_rules)
        self.assertIsNone(measured["com"])
        self.assertEqual(measured["bbox"], [0.0, 0.0, 0.0, 1.0, 1.0, 1.0])

    def test_a_null_centre_survives_normalising_and_writing(self):
        """`com: null` must reach the file, not raise while rounding floats."""
        measured = cad_fingerprint._measure_shape(_Shape(), cad_fingerprint.cad_rules)
        self.assertIsNone(cad_rules.normalise({"objects": {"X": measured}})
                          ["objects"]["X"]["com"])


class TestMeasuredNothing(unittest.TestCase):
    """An empty fingerprint that reports success is how the bug stayed hidden."""

    def test_every_object_failing_is_reported(self):
        self.assertTrue(cad_rules.measured_nothing({"objects": {}, "errors": ["X: boom"]}))

    def test_a_document_with_no_geometry_stays_quiet(self):
        """A spreadsheet measures nothing and that is correct."""
        self.assertFalse(cad_rules.measured_nothing({"objects": {}, "errors": []}))

    def test_one_broken_feature_among_many_is_not_the_same_thing(self):
        self.assertFalse(
            cad_rules.measured_nothing({"objects": {"Pad": {}}, "errors": ["X: boom"]}))


class TestSkippedTypes(unittest.TestCase):
    def test_every_origin_datum_is_skipped(self):
        """The origin's point was missing while its line and plane were listed."""
        for type_id in ("App::Origin", "App::Line", "App::Plane", "App::Point"):
            self.assertTrue(
                type_id.startswith(cad_rules.SKIPPED_TYPE_PREFIXES),
                f"{type_id} should be skipped",
            )

    def test_real_content_is_not_skipped(self):
        for type_id in ("App::Part", "App::Link", "Assembly::AssemblyObject",
                        "PartDesign::Body", "PartDesign::Pad", "Part::Feature"):
            self.assertFalse(
                type_id.startswith(cad_rules.SKIPPED_TYPE_PREFIXES),
                f"{type_id} should be measured",
            )


class _Object:
    """A stand-in for a FreeCAD document object, with whatever `Shape` holds."""

    def __init__(self, name, type_id, shape=None):
        self.Name = name
        self.Label = name
        self.TypeId = type_id
        if shape is not None:
            self.Shape = shape


class _Document:
    def __init__(self, objects):
        self.Objects = objects
        self.Name = "doc"


class TestShapedObjects(unittest.TestCase):
    """`Shape` does not always hold a shape, and one exception lost a document."""

    def test_a_shape_property_that_links_to_an_object_is_skipped(self):
        """A FEM mesh points `Shape` at the part it was meshed from.

        The link is a document object, so every shape method on it raises. That
        happened inside the generator, where the caller's per-object `except`
        could not catch it, and the whole document went unmeasured.
        """
        pad = _Object("Pad", "PartDesign::Pad", shape=_Shape(centre_of_mass=(1.0, 2.0, 3.0)))
        mesh = _Object("FEMMeshNetgen", "Fem::FemMeshShapeNetgenObject", shape=pad)
        measured = list(cad_fingerprint._shaped_objects(
            _Document([pad, mesh]), cad_fingerprint.cad_rules))
        self.assertEqual([obj.Name for obj, _ in measured], ["Pad"])

    def test_a_document_of_one_fem_mesh_still_measures_its_geometry(self):
        """The regression that mattered: one mesh must not cost every object."""
        shapes = [
            _Object(f"Pad{index}", "PartDesign::Pad", shape=_Shape(centre_of_mass=(0.0, 0.0, 0.0)))
            for index in range(3)
        ]
        mesh = _Object("FEMMeshGmsh", "Fem::FemMeshShapeBaseObjectPython", shape=shapes[0])
        measured = list(cad_fingerprint._shaped_objects(
            _Document([mesh, *shapes]), cad_fingerprint.cad_rules))
        self.assertEqual(len(measured), 3)

    def test_an_object_with_no_shape_at_all_is_skipped(self):
        spreadsheet = _Object("Params", "Spreadsheet::Sheet")
        measured = list(cad_fingerprint._shaped_objects(
            _Document([spreadsheet]), cad_fingerprint.cad_rules))
        self.assertEqual(measured, [])


class _ViewObject:
    def __init__(self):
        self.Visibility = False


class _TreeObject:
    """A FreeCAD object with a type, a label and, for containers, a Group.

    It starts hidden, which is how a new part opened after a headless build.
    """

    def __init__(self, doc, type_id, name):
        self.TypeId = type_id
        self.Name = name
        self.Label = name
        self.Group = []
        self.Visibility = False
        self.ViewObject = _ViewObject() if doc.gui else None
        self.Placement = types.SimpleNamespace(Rotation=None)
        self.expressions = {}
        self._doc = doc

    def setExpression(self, path, expr):
        self.expressions[path] = expr

    def addObject(self, obj):
        # FreeCAD moves the object out of any other group it was in.
        for other in self._doc.Objects:
            if obj in other.Group:
                other.Group.remove(obj)
        self.Group.append(obj)


#: FreeCAD gives each of these its own coordinate system when it is created.
_HAS_ORIGIN = ("App::Part", "PartDesign::Body", "Assembly::AssemblyObject")
_ORIGIN_FEATURES = (
    ("App::Line", "X_Axis"), ("App::Line", "Y_Axis"), ("App::Line", "Z_Axis"),
    ("App::Plane", "XY_Plane"), ("App::Plane", "XZ_Plane"),
    ("App::Plane", "YZ_Plane"), ("App::Point", "Origin_Point"),
)


class _TreeDocument:
    def __init__(self, file_name="/m/rail/cad/rail.FCStd", gui=False):
        self.Name = "rail"
        self.FileName = file_name
        self.Objects = []
        self.journal = []
        self.gui = gui

    def addObject(self, type_id, name):
        obj = self._add(type_id, name)
        if type_id == cad_rules.FRAME_TYPE:
            # A frame owns its axes and planes directly. They start hidden
            # here, so a test proves that the build shows them.
            obj.OriginFeatures = [self._add(t, n) for t, n in _ORIGIN_FEATURES]
        if type_id in _HAS_ORIGIN:
            # The origin starts visible here, so a test proves that the build
            # hides it and does not only leave it as it was.
            origin = self._add("App::Origin", "Origin")
            origin.OriginFeatures = [self._add(t, n) for t, n in _ORIGIN_FEATURES]
            for item in [origin, *origin.OriginFeatures]:
                item.Visibility = True
            obj.Origin = origin
        return obj

    def _add(self, type_id, name):
        taken = {o.Name for o in self.Objects}
        unique, n = name, 0
        while unique in taken:
            n += 1
            unique = f"{name}{n:03d}"
        obj = _TreeObject(self, type_id, unique)
        self.Objects.append(obj)
        return obj

    def shapes(self):
        """The objects that are not part of a coordinate system."""
        return [o for o in self.Objects if o.TypeId not in cad_rules.ORIGIN_TYPES]

    def origins(self):
        return [o for o in self.Objects if o.TypeId in cad_rules.ORIGIN_TYPES]

    def getObjectsByLabel(self, label):
        return [o for o in self.Objects if o.Label == label]

    def openTransaction(self, name):
        self.journal.append("open")

    def commitTransaction(self):
        self.journal.append("commit")

    def abortTransaction(self):
        self.journal.append("abort")

    def recompute(self):
        pass

    def save(self):
        self.journal.append("save")


class TestPartContainerHelpers(unittest.TestCase):
    """An agent gets its Body through body(), so the top object is a Part."""

    def test_body_is_created_inside_a_part(self):
        doc = _TreeDocument()
        b = cad_build.body(doc)
        top = cad_build.part(doc)
        self.assertEqual(top.TypeId, "App::Part")
        self.assertEqual(top.Label, "rail")
        self.assertEqual(top.Group, [b])
        cad_build.check_part_container(doc)  # does not raise

    def test_a_rebuild_adds_nothing(self):
        doc = _TreeDocument()
        first = cad_build.body(doc)
        again = cad_build.body(doc)
        self.assertIs(first, again)
        self.assertEqual(len(doc.shapes()), 2)

    def test_an_old_body_on_top_is_moved_into_the_part(self):
        doc = _TreeDocument()
        old = doc.addObject("PartDesign::Body", "Body")
        self.assertIs(cad_build.body(doc), old)
        self.assertEqual(cad_build.part(doc).Group, [old])

    def test_a_body_on_top_stops_the_build(self):
        doc = _TreeDocument()
        doc.addObject("PartDesign::Body", "Body")
        with self.assertRaisesRegex(RuntimeError, "not inside a Part container: Body"):
            cad_build.check_part_container(doc)

    def test_an_assembly_document_is_not_checked(self):
        doc = _TreeDocument("/m/x-axis/cad/assemblies/x-axis.FCStd")
        doc.addObject("PartDesign::Body", "Body_master")
        cad_build.check_part_container(doc)  # does not raise


class TestFrameHelper(unittest.TestCase):
    """A mounting frame sits in the Part and is placed by expressions."""

    def test_frame_is_created_in_the_part_with_expressions(self):
        doc = _TreeDocument()
        f = cad_build.frame(doc, "IF_mount_bottom", x="Params.rail_l / 2", z="Params.rail_h")
        self.assertEqual(f.TypeId, "Part::LocalCoordinateSystem")
        self.assertEqual(f.Label, "IF_mount_bottom")
        self.assertIn(f, cad_build.part(doc).Group)
        self.assertEqual(f.expressions, {"Placement.Base.x": "Params.rail_l / 2",
                                         "Placement.Base.z": "Params.rail_h"})

    def test_a_rebuild_reuses_the_frame(self):
        doc = _TreeDocument()
        first = cad_build.frame(doc, "IF_mount_bottom", x="Params.a")
        again = cad_build.frame(doc, "IF_mount_bottom", x="Params.b")
        self.assertIs(first, again)
        self.assertEqual(again.expressions["Placement.Base.x"], "Params.b")
        frames = [o for o in doc.Objects if o.TypeId == "Part::LocalCoordinateSystem"]
        self.assertEqual(len(frames), 1)

    def test_an_angle_sets_the_axis_and_drives_the_angle(self):
        doc = _TreeDocument()
        fake = types.SimpleNamespace(
            Vector=lambda *v: v, Rotation=lambda axis, angle: ("rot", axis, angle))
        with mock.patch.dict(sys.modules, {"FreeCAD": fake}):
            f = cad_build.frame(doc, "IF_motor", angle="Params.motor_a", axis=(1, 0, 0))
        self.assertEqual(f.Placement.Rotation, ("rot", (1, 0, 0), 0))
        self.assertEqual(f.expressions, {"Placement.Rotation.Angle": "Params.motor_a"})

    def test_a_label_without_the_prefix_is_refused(self):
        with self.assertRaisesRegex(ValueError, "must start with 'IF_'"):
            cad_build.frame(_TreeDocument(), "mount_bottom")


class TestNewObjectsAreVisible(unittest.TestCase):
    """A new part or assembly opens visible; its coordinate system stays hidden."""

    def _run(self, build_fn, doc):
        with mock.patch.object(cad_build, "open_document", return_value=(doc, False)), \
                mock.patch.object(cad_build.cad_fingerprint, "read_params", return_value={}), \
                mock.patch.object(cad_build.cad_fingerprint, "write"):
            cad_build.run(build_fn)

    def test_body_shows_the_part_and_the_body(self):
        doc = _TreeDocument()
        b = cad_build.body(doc)
        self.assertTrue(cad_build.part(doc).Visibility)
        self.assertTrue(b.Visibility)
        self.assertEqual(len(doc.origins()), 16)
        self.assertFalse(any(o.Visibility for o in doc.origins()))

    def test_gui_view_is_set_too(self):
        doc = _TreeDocument(gui=True)
        b = cad_build.body(doc)
        self.assertTrue(b.ViewObject.Visibility)
        self.assertFalse(b.Origin.ViewObject.Visibility)

    def test_run_shows_an_assembly_its_links_and_the_body_tip(self):
        doc = _TreeDocument("/m/x-axis/cad/assemblies/x-axis.FCStd")

        def build(d, params):
            d.addObject("Assembly::AssemblyObject", "Assembly")
            d.addObject("App::Link", "Rail")
            master = d.addObject("PartDesign::Body", "Body_master")
            master.Tip = d.addObject("PartDesign::Pad", "Pad")
            d.addObject("Sketcher::SketchObject", "Sketch")

        self._run(build, doc)
        shown = {o.Name for o in doc.shapes() if o.Visibility}
        self.assertEqual(shown, {"Assembly", "Rail", "Body_master", "Pad"})
        self.assertEqual(len(doc.origins()), 16)
        self.assertFalse(any(o.Visibility for o in doc.origins()))

    def test_an_object_hidden_before_the_build_stays_hidden(self):
        doc = _TreeDocument()
        b = cad_build.body(doc)
        b.Visibility = False
        self._run(lambda d, p: cad_build.body(d), doc)
        self.assertFalse(b.Visibility)

    def test_a_new_frame_shows_with_its_axes(self):
        doc = _TreeDocument()
        f = cad_build.frame(doc, "IF_mount")
        self.assertTrue(f.Visibility)
        self.assertEqual(len(f.OriginFeatures), 7)
        self.assertTrue(all(o.Visibility for o in f.OriginFeatures))
        # The Part container's own coordinate system stays hidden.
        self.assertFalse(cad_build.part(doc).Origin.Visibility)

    def test_run_shows_an_imported_solid_and_a_frame_but_not_the_origin(self):
        doc = _TreeDocument()

        def build(d, params):
            container = cad_build.part(d)
            container.addObject(d.addObject("Part::Feature", "Part__Feature"))
            cad_build.frame(d, "IF_rail", container=container)

        self._run(build, doc)
        by_name = {o.Name: o for o in doc.Objects}
        self.assertTrue(by_name["Part__Feature"].Visibility)
        self.assertTrue(by_name["Frame"].Visibility)
        self.assertTrue(all(o.Visibility for o in by_name["Frame"].OriginFeatures))
        self.assertFalse(by_name["Origin"].Visibility)
        self.assertFalse(any(o.Visibility for o in by_name["Origin"].OriginFeatures))

    def test_a_frame_a_person_hid_stays_hidden_on_a_rerun(self):
        doc = _TreeDocument()
        f = cad_build.frame(doc, "IF_mount")
        f.Visibility = False
        self._run(lambda d, p: cad_build.frame(d, "IF_mount"), doc)
        self.assertFalse(f.Visibility)


class TestRunChecksTheTree(unittest.TestCase):
    """run() undoes a build that leaves a Body on top, and saves nothing."""

    def _run(self, build_fn):
        doc = _TreeDocument()
        with mock.patch.object(cad_build, "open_document", return_value=(doc, False)), \
                mock.patch.object(cad_build.cad_fingerprint, "read_params", return_value={}), \
                mock.patch.object(cad_build.cad_fingerprint, "write"):
            try:
                cad_build.run(build_fn)
            except RuntimeError as err:
                return doc, err
        return doc, None

    def test_body_on_top_aborts_the_transaction(self):
        doc, err = self._run(lambda d, p: d.addObject("PartDesign::Body", "Body"))
        self.assertIn("not inside a Part container", str(err))
        self.assertEqual(doc.journal, ["open", "abort"])

    def test_body_inside_a_part_commits_and_saves(self):
        doc, err = self._run(lambda d, p: cad_build.body(d))
        self.assertIsNone(err)
        self.assertEqual(doc.journal, ["open", "commit", "save"])


if __name__ == "__main__":
    unittest.main()
