"""Resolve an instance module: the machine's choice of family variant.

A Git submodule is a frozen mirror of another repository — there is no slot
inside it for "my machine wants the 500 mm servo version".  So the consumer
repo keeps a small folder of its own that holds the **choice**, never the
design::

    modules/x-stage/
      okh.toml                    [instance] — family, composition, model
      cad/x-stage.FCStd           Variant Link into the family, Configuration set
      cad/resolved/params.csv     generated, COMMITTED
      cad/resolved/vendor-cad.csv generated, COMMITTED
      cad/resolved/provenance.toml
      bom/bom.csv                 this instance's own rows, resolved
      bom/resolved.csv            flattened purchasing list, COMMITTED

The generated files are committed on purpose: their git diff is exactly "what
did the family update change for *my* variant", which is the review surface
that stops a supplier change reaching purchasing unseen.  ``--check`` fails
when they are stale, so forgetting is caught by CI rather than by an invoice.
"""
from __future__ import annotations

import argparse
import csv
import io
import tomllib
from pathlib import Path

from naming_rules import BOM_HEADERS, is_under_tooling_submodule, repo_root_from_script
from param_rules import (
    PARAM_HEADERS,
    ParamError,
    load_param_csv,
    merge_params,
    params_dir,
    resolve as resolve_params_values,
)
from resolve_bom import BomError, load_sources, collect_vendor
import resolve_bom

RESOLVED_DIR = Path("cad") / "resolved"
RESOLVED_PARAMS = RESOLVED_DIR / "params.csv"
RESOLVED_VENDOR = RESOLVED_DIR / "vendor-cad.csv"
PROVENANCE = RESOLVED_DIR / "provenance.toml"
RESOLVED_BOM = Path("bom") / "resolved.csv"

GENERATED = (
    "GENERATED by doqs/scripts/resolve_instance.py -- do not edit by hand.\n"
    "Change [instance] in okh.toml, or the family, then re-run the resolver."
)
VENDOR_HEADERS = ("module", "id", "cad", "envelope", "terms")
RESOLVED_BOM_HEADERS = ("module", *BOM_HEADERS)


class InstanceError(Exception):
    """Raised when an instance declaration does not resolve against its family."""


def load_toml(path: Path) -> dict:
    with open(path, "rb") as f:
        return tomllib.load(f)


def instance_modules(root: Path) -> list[Path]:
    """Every module under ``root`` whose okh.toml carries an ``[instance]`` table."""
    found: list[Path] = []
    for okh in sorted(root.rglob("okh.toml")):
        if is_under_tooling_submodule(okh, root):
            continue
        try:
            if "instance" in load_toml(okh):
                found.append(okh.parent)
        except tomllib.TOMLDecodeError:
            continue
    return found


def _require(spec: dict, key: str, where: str) -> str:
    value = spec.get(key)
    if not value:
        raise InstanceError(f"{where}: [instance] is missing {key!r}")
    return str(value)


def targets(root: Path, instance_dir: Path) -> dict:
    """Resolve the family, composition, core and option directories."""
    okh = instance_dir / "okh.toml"
    spec = load_toml(okh).get("instance", {})
    where = okh.relative_to(root).as_posix()

    family = root / _require(spec, "family", where)
    if not (family / "okh.toml").exists():
        raise InstanceError(
            f"{where}: family {spec['family']!r} has no okh.toml — "
            "is the submodule checked out? (git submodule update --init)"
        )
    composition = family / _require(spec, "composition", where)
    if not (composition / "okh.toml").exists():
        raise InstanceError(
            f"{where}: the family does not contain composition {spec['composition']!r}. "
            "It may have been renamed or discontinued upstream."
        )

    comp_manifest = load_toml(composition / "okh.toml")
    comp = comp_manifest.get("composition", {})
    if "core" not in comp:
        raise InstanceError(
            f"{spec['composition']}/okh.toml: missing [composition] core"
        )
    core = family / comp["core"]
    if not (core / "okh.toml").exists():
        raise InstanceError(f"{spec['composition']}: core {comp['core']!r} not found")

    options = []
    for option in comp.get("options", []):
        option_dir = family / option
        if not (option_dir / "okh.toml").exists():
            raise InstanceError(f"{spec['composition']}: option {option!r} not found")
        options.append((option, option_dir))

    model = _require(spec, "model", where)
    declared = {m.get("name") for m in load_toml(core / "okh.toml").get("model", [])}
    if declared and model not in declared:
        raise InstanceError(
            f"{where}: the core no longer declares model {model!r} "
            f"(available: {', '.join(sorted(n for n in declared if n))})"
        )

    return {
        "spec": spec, "family": family, "family_rel": spec["family"],
        "composition": composition, "composition_rel": spec["composition"],
        "core": core, "core_rel": comp["core"], "options": options,
        "model": model, "sku": spec.get("sku", ""),
        "family_version": load_toml(family / "okh.toml").get("version", "?"),
    }


def resolved_params(instance_dir: Path, target: dict) -> dict[str, dict[str, str]]:
    """Core defaults + the model override + any instance-local override."""
    merged = load_param_csv(params_dir(target["core"]) / "default.csv")
    if target["model"] != "default":
        merged = merge_params(merged, load_param_csv(
            params_dir(target["core"]) / f"{target['model']}.csv"))
    extra = target["spec"].get("params")
    if extra:
        extra_path = instance_dir / extra
        if not extra_path.exists():
            raise InstanceError(f"[instance] params not found: {extra}")
        merged = merge_params(merged, load_param_csv(extra_path))
    values = resolve_params_values(merged)
    return {a: {**row, "value": values.get(a, row.get("value", ""))}
            for a, row in merged.items()}


def _csv(headers, rows, *, comments: str = "") -> str:
    buffer = io.StringIO()
    for line in comments.strip().splitlines() if comments else []:
        buffer.write(f"# {line}\n")
    writer = csv.DictWriter(buffer, fieldnames=list(headers), lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow({k: row.get(k, "") for k in headers})
    return buffer.getvalue()


def render_all(root: Path, instance_dir: Path) -> dict[Path, str]:
    """Build every generated file for one instance, as ``relative path -> content``."""
    target = targets(root, instance_dir)
    model = target["model"]
    params = resolved_params(instance_dir, target)
    values = {a: r["value"] for a, r in params.items()}

    # Every module in the composition, resolved against the SAME parameter set.
    members = [(target["core_rel"], target["core"]), *target["options"]]
    members.append((target["composition_rel"], target["composition"]))

    bom_rows: list[dict[str, str]] = []
    vendor_rows: list[dict[str, str]] = []
    own_rows: list[dict[str, str]] = []
    for rel, directory in members:
        rows, vendor = _resolve_member(directory, model, rel, values)
        if directory == target["composition"]:
            own_rows = rows
        for row in rows:
            bom_rows.append({"module": rel, **row})
        vendor_rows.extend(vendor)

    provenance = "\n".join([
        f"# {line}" for line in GENERATED.splitlines()
    ] + [
        "",
        'schema = "doqs-instance-v1"',
        f'family = "{target["family_rel"]}"',
        f'family-version = "{target["family_version"]}"',
        f'composition = "{target["composition_rel"]}"',
        f'model = "{model}"',
        f'sku = "{target["sku"]}"',
        f"parameters = {len(params)}",
        f"bom-rows = {len(bom_rows)}",
        "",
    ])

    out: dict[Path, str] = {
        RESOLVED_PARAMS: _csv(PARAM_HEADERS,
                              [params[a] for a in sorted(params)],
                              comments=f"{GENERATED}\nmodel: {model}"),
        RESOLVED_BOM: _csv(RESOLVED_BOM_HEADERS, bom_rows),
        RESOLVED_VENDOR: _csv(VENDOR_HEADERS, vendor_rows),
        PROVENANCE: provenance,
    }
    if own_rows:
        # The instance's own bom/bom.csv keeps the plain 16-column DOQS header
        # with no comment lines, so check_names reads it like any other BOM.
        out[Path("bom") / "bom.csv"] = resolve_bom.render(own_rows)
    return out


def _resolve_member(directory: Path, model: str, rel: str, values: dict[str, str]):
    """Resolve one member module, injecting the composition-wide parameters."""
    bom_path = directory / "bom" / "bom.csv"
    if not bom_path.exists():
        return [], []
    rows = resolve_bom.load_bom(bom_path)
    overlay = directory / "bom" / "models" / f"{model}.csv"
    if overlay.exists():
        rows = resolve_bom.apply_overlay(rows, overlay)
    sources = load_sources(directory)
    resolve_bom.apply_bindings(rows, directory, values, sources)
    resolve_bom.apply_templates(rows, values)
    vendor = collect_vendor(rows, directory, values, sources, rel)
    return rows, vendor


def process(root: Path, instance_dir: Path, *, check: bool) -> bool:
    rel_instance = instance_dir.relative_to(root).as_posix()
    try:
        rendered = render_all(root, instance_dir)
    except (InstanceError, BomError, ParamError) as exc:
        print(f"FAIL  {rel_instance}")
        print(f"      {exc}")
        return False

    ok = True
    for rel_path, content in sorted(rendered.items()):
        path = instance_dir / rel_path
        rel = f"{rel_instance}/{rel_path.as_posix()}"
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            print(f"ok    {rel}")
            continue
        if check:
            print(f"FAIL  {rel}")
            print(f"      {'missing' if current is None else 'stale'} — "
                  "re-run resolve_instance.py and commit the result")
            ok = False
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {rel}")
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description="Resolve DOQS instance modules.")
    parser.add_argument("--root", type=Path, default=None)
    parser.add_argument("module", nargs="?", type=Path, default=None,
                        help="Instance module directory (default: all under --root)")
    parser.add_argument("--check", action="store_true",
                        help="Do not write; exit non-zero if any output is stale")
    args = parser.parse_args()

    root = args.root.resolve() if args.root else repo_root_from_script()
    instances = [(root / args.module).resolve()] if args.module else instance_modules(root)
    if not instances:
        print("No instance modules found (no okh.toml with an [instance] table)")
        return 0

    all_ok = all([process(root, d, check=args.check) for d in instances])
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
