"""Resolve parametric models: sparse override CSVs -> active params and config table.

Two outputs, deliberately different in lifecycle:

``cad/params.csv``
    The single **active** model, consumed by ``cad_sync_params.py`` and the BOM
    resolver.  Generated and gitignored, exactly as before.

``cad/params-table.csv``
    Dense: one row per declared model.  **Committed.**  ``cad_sync_params.py``
    writes it into the FreeCAD spreadsheet as a Configuration Table, which is
    what gives a composition document a ``Configuration`` enum whose values are
    the model slugs — and therefore what lets a parent machine variant-link the
    composition and pick a length.  See ``docs/variants.md``.
"""
from __future__ import annotations

import argparse
import csv
import io
from pathlib import Path

from naming_rules import is_under_tooling_submodule, repo_root_from_script
from param_rules import (
    PARAM_HEADERS,
    ParamError,
    declared_models,
    params_dir,
    resolve_model,
    write_param_csv,
)

ACTIVE_NAME = "params.csv"
TABLE_NAME = "params-table.csv"
TABLE_KEY = "configuration"

GENERATED_HEADER = (
    "GENERATED by doqs/scripts/resolve_params.py -- do not edit by hand.\n"
    "Edit cad/params/default.csv and cad/params/<model>.csv instead."
)


def parametric_modules(root: Path) -> list[Path]:
    """Every module under ``root`` that has a ``cad/params/default.csv``."""
    found: list[Path] = []
    for default_csv in sorted(root.rglob("cad/params/default.csv")):
        if is_under_tooling_submodule(default_csv, root):
            continue
        found.append(default_csv.parent.parent.parent)
    return found


def render_active(module_dir: Path, model: str) -> str:
    rows = resolve_model(module_dir, model)
    buffer = io.StringIO()
    for line in GENERATED_HEADER.splitlines():
        buffer.write(f"# {line}\n")
    buffer.write(f"# model: {model}\n")
    writer = csv.DictWriter(buffer, fieldnames=list(PARAM_HEADERS), lineterminator="\n")
    writer.writeheader()
    for alias in sorted(rows):
        writer.writerow({k: rows[alias].get(k, "") for k in PARAM_HEADERS})
    return buffer.getvalue()


def render_table(module_dir: Path) -> str:
    """Dense configuration table: one row per model, one column per alias."""
    models = declared_models(module_dir)
    resolved = {m: resolve_model(module_dir, m) for m in models}
    aliases: list[str] = sorted({a for rows in resolved.values() for a in rows})

    buffer = io.StringIO()
    for line in GENERATED_HEADER.splitlines():
        buffer.write(f"# {line}\n")
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow([TABLE_KEY, *aliases])
    for model in models:
        rows = resolved[model]
        writer.writerow([model, *(rows.get(a, {}).get("value", "") for a in aliases)])
    return buffer.getvalue()


def _emit(path: Path, content: str, *, check: bool, rel: str) -> bool:
    """Write ``content`` to ``path``; in check mode only report staleness."""
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        print(f"ok    {rel}")
        return True
    if check:
        state = "missing" if current is None else "stale"
        print(f"FAIL  {rel}")
        print(f"      {state} — re-run resolve_params.py and commit the result")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {rel}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="Resolve DOQS parametric models.")
    parser.add_argument("--root", type=Path, default=None,
                        help="Machine repo root (default: parent of doqs/ submodule)")
    parser.add_argument("--module", type=Path, default=None,
                        help="Single module directory, relative to --root")
    parser.add_argument("--model", default=None,
                        help="Model slug to write to cad/params.csv (default: skip)")
    parser.add_argument("--table", action="store_true",
                        help="Write the committed dense cad/params-table.csv")
    parser.add_argument("--check", action="store_true",
                        help="Do not write; exit non-zero if any output is stale")
    args = parser.parse_args()

    root = args.root.resolve() if args.root else repo_root_from_script()
    if args.module:
        modules = [(root / args.module).resolve()]
    else:
        modules = parametric_modules(root)

    if not modules:
        print("No modules with cad/params/default.csv found")
        return 0
    if args.model is None and not args.table:
        args.table = True

    all_ok = True
    for module_dir in modules:
        rel_module = module_dir.relative_to(root).as_posix()
        if not (params_dir(module_dir) / "default.csv").exists():
            print(f"FAIL  {rel_module}")
            print("      no cad/params/default.csv")
            all_ok = False
            continue
        try:
            if args.model is not None:
                all_ok &= _emit(
                    module_dir / "cad" / ACTIVE_NAME,
                    render_active(module_dir, args.model),
                    check=args.check,
                    rel=f"{rel_module}/cad/{ACTIVE_NAME}",
                )
            if args.table:
                all_ok &= _emit(
                    module_dir / "cad" / TABLE_NAME,
                    render_table(module_dir),
                    check=args.check,
                    rel=f"{rel_module}/cad/{TABLE_NAME}",
                )
        except ParamError as exc:
            print(f"FAIL  {rel_module}")
            print(f"      {exc}")
            all_ok = False

    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
